In [6]:
import numpy as np
a= np.array([2,3,5,7,11,13,17,19])
a_maggiore10= a>10
print(a_maggiore10) 
a_pari=a[a%2==0]
print(a_pari)

[False False False False  True  True  True  True]
[2]


2. Operazioni su array
Crea un array a, 2D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente la sua 2ª e 4ª riga, e c contenente solo la 3ª. Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [19]:
from numpy import *
a =array([array([i for i in range(1,11)])* j for j in range(1,11)])
print(a)
b=a[[1,3],]
c=a[2,]
print("\n\n",b,"\n\n",c)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


 [[ 2  4  6  8 10 12 14 16 18 20]
 [ 4  8 12 16 20 24 28 32 36 40]] 

 [ 3  6  9 12 15 18 21 24 27 30]


3. Seleziona il numero più vicino a 0.5 in un array casuale
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1]. Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [17]:
import numpy as np
a= np.random.rand(10,3)
print(a)
colonna = np.abs(a - 0.5).argmin(axis=1)
righe = np.arange(10)# .arrange(a.shape[0])
nuovo= a[righe,colonna]
print(nuovo)

[[0.22365146 0.17816829 0.31364049]
 [0.95128971 0.02444514 0.52937349]
 [0.46808983 0.95998635 0.5392923 ]
 [0.55208352 0.48106329 0.57206177]
 [0.02355619 0.86858431 0.04521368]
 [0.1947797  0.5192237  0.37779564]
 [0.29255331 0.26027456 0.02165976]
 [0.43064411 0.20336308 0.03966904]
 [0.67664877 0.36564788 0.64204799]
 [0.88524616 0.43354024 0.2365632 ]]
[0.31364049 0.52937349 0.46808983 0.48106329 0.86858431 0.5192237
 0.29255331 0.43064411 0.36564788 0.43354024]


4. Analisi della Frequenza Cardiaca con NumPy
       1-Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca registrata dal tuo Fitbit durante la giornata:
       68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70
       Inserisci questi valori in un array NumPy.

       2-Trova la frequenza cardiaca minima registrata durante la giornata.
       (Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)

       3- Trova la frequenza cardiaca massima registrata durante la giornata.
       (Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)

       4-Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120):

       -Crea un nuovo array che contiene True quando la frequenza cardiaca è superiore a 120, e False quando è inferiore o uguale a 120.
       Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.

In [24]:
import numpy as np
freq= np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print('frequenza:')
print(freq)

min_freq= freq.min()
print("min-frequenza:",min_freq)
 
max_freq=freq.max()
print("max_freq:",max_freq)

freq_superiore_120=freq>120
print('frequenza_superiore_120:')
print(freq_superiore_120)

freq_superiore_120_percentuale=np.mean(freq_superiore_120)*100
print(f"frequenza_superiore_120_percentuale:{freq_superiore_120_percentuale}%")


frequenza:
[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]
min-frequenza: 60
max_freq: 164
frequenza_superiore_120:
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
frequenza_superiore_120_percentuale:52.38095238095239%
